# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: cfmleditor.clif
PackageVersion: 0.5.1
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: clif.exe
    PortableCommandAlias: clif
  InstallerUrl: https://github.com/cfmleditor/clif/releases/download/v0.5.1/clif-windows-amd64.zip
  InstallerSha256: 338CA558BFF681B46A9C4C83FA9BC6081C972E3445EC5EAC0CB36F88015F921A
ManifestType: installer
ManifestVersion: 1.12.0
